In [11]:
import numpy as np
nums_list=[10,12,14,16,20]
nums_array=np.array(nums_list)
type(nums_array)

numpy.ndarray

In [14]:
arr=np.arange(1, 5)
print(arr)

[1 2 3 4]


In [16]:
arr2=np.ones(6)
print(arr2)

[1. 1. 1. 1. 1. 1.]


In [19]:
arr=np.random.rand(5,4)
print(arr)

[[0.85193597 0.54439315 0.81224939 0.86902911]
 [0.1471686  0.69598383 0.52384034 0.85139112]
 [0.41923891 0.91780453 0.26574556 0.73709615]
 [0.66969317 0.361798   0.78416513 0.22835705]
 [0.15508269 0.49221024 0.43176955 0.68123227]]


In [4]:
import pandas as pd
titanic_data = pd.read_csv(r"titanic_data.csv")
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
titanic_survived = (titanic_data.Survived == 1)
titanic_survived_data = titanic_data[titanic_survived]
titanic_survived_data.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [8]:
ages = [20, 21, 22]
age_dataset = titanic_data[titanic_data["Age"].isin(ages)]
age_dataset.head()

PassengerId  Survived  Pclass                            Name     Sex  \
0             1         0       3         Braund, Mr. Owen Harris    male   
12           13         0       3  Saundercock, Mr. William Henry    male   
37           38         0       3        Cann, Mr. Ernest Charles    male   
51           52         0       3    Nosworthy, Mr. Richard Cater    male   
56           57         1       2               Rugg, Miss. Emily  female   

     Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
0   22.0      1      0   A/5 21171   7.25   NaN        S  
12  20.0      0      0   A/5. 2151   8.05   NaN        S  
37  21.0      0      0  A./5. 2152   8.05   NaN        S  
51  21.0      0      0  A/4. 39886   7.80   NaN        S  
56  21.0      0      0  C.A. 31026  10.50   NaN        S

In [10]:
titanic_pclass1_data = titanic_data[titanic_data.Pclass == 1]
print(titanic_pclass1_data.shape)
titanic_pclass2_data = titanic_data[titanic_data.Pclass == 2]
print(titanic_pclass2_data.shape)

(216, 12)
(184, 12)


In [11]:
titanic_pclass_both = titanic_pclass1_data.append(titanic_pclass2_data, ignore_index = True)
print(titanic_pclass_both.shape)

(400, 12)


In [14]:
titanic_pclass_both2 = pd.concat([titanic_pclass1_data, titanic_pclass2_data])
print(titanic_pclass_both2.shape)

(400, 12)


In [15]:
def mult(x):
    return x*2
updated_data = titanic_data.Pclass.apply(mult)
updated_data.head()

0    6
1    2
2    6
3    2
4    6
Name: Pclass, dtype: int64

In [18]:
def substractFare(fare):
    return fare - 10
substracted_fare = titanic_data.Fare.apply(substractFare)
substracted_fare.head()

0    -2.7500
1    61.2833
2    -2.0750
3    43.1000
4    -1.9500
Name: Fare, dtype: float64